### ISSUE TITLE
Cycle Sort [SWOC]

### ISSUE THREAD

**Issue by HardevKhandhar** [edualgo/eduAlgo#108]
I am a participant of SWOC 2021, I would like to contribute by adding the code for Cycle Sort.  
Kindly assign this issue to me.
Thank you.

**Comment by ayushi-get** [comment]
I would love to work on this issue ,i m a participant of SWOC.
Please assign this issue to me

**Comment by Abhijit2505** [comment]
@HardevKhandhar please get started
