### ISSUE TITLE
Important greedy algorithms addition in the repository(SWOC)

### ISSUE THREAD

**Issue by spursbyte** [edualgo/eduAlgo#111]
I wish to contribute some important greedy algorithms like maximizing sum of absolute difference in an array,Water Connection problem,activity selection problem.Kindly assign me the issue.

**Comment by Abhijit2505** [comment]
@spursbyte, please create issues for each problem, don't conserve an entire department of Greedy Algo in your issue.

Closing the issue, please create issues for each algorithms.
