### ISSUE TITLE
A* Pathfinding Algorithm with GUI

### ISSUE THREAD

**Issue by proghead00** [edualgo/eduAlgo#112]
**Is your feature request related to a problem? Please describe.**
It is a feature for additional enhancement

**Describe the solution you'd like**
This is a feature that helps to find the shortest distance between two nodes. It uses pygame, and has keys functionalities that even a layman can use.

**Describe alternatives you've considered**
Alternatives include creating the same without a GUI

**Comment by Abhijit2505** [comment]
Well, no need of PyGame and GUI, just add the A* algorithm.

@proghead00 please get started.
