### ISSUE TITLE
JOB SEQUENCING PROBLEM IMPLEMENTATION USING GREEDY ALGO IN PYTHON[SWOC21]

### ISSUE THREAD

**Issue by spursbyte** [edualgo/eduAlgo#113]
An array of jobs is given  where every job has a deadline and associated profit if the job is finished before the deadline. It is also given that every job takes the single unit of time, so the minimum possible deadline for any job is 1. finding a way to maximize total profit if only one job can be scheduled at a time.

**Comment by Abhijit2505** [comment]
@spursbyte although you have pasted a question copied from some website here, you should focus on making the algorithm and the code dynamic.

We have the software and we are not doing programming problems here.

Do get started and add the algorithm only.
