### ISSUE TITLE
Add Binary Search Tree implementation

### ISSUE THREAD

**Issue by shubhigupta991** [edualgo/eduAlgo#115]
Binary Search tree implementation
I will include functions for insertion lookup deletion.
Also i want to include Breadth First Tree and Depth Search Tree algorithms.

**Comment by shubhigupta991** [comment]
Please assign me this issue.

**Comment by jatinjain001** [comment]
I want to work on this issue. Please let me know if it is available

**Comment by Abhijit2505** [comment]
> Binary Search tree implementation
> I will include functions for insertion lookup deletion.
> Also i want to include Breadth First Tree and Depth Search Tree algorithms.

Well, please check the eduAlgo package documentations, binary tree implementations are already present.

DFS and BFS section will be covered in the graph module.

Closing the issue.
