### ISSUE TITLE
Randomized quick sort [SwoC]

### ISSUE THREAD

**Issue by AdityaArunSharma** [edualgo/eduAlgo#116]
**Is your feature request related to a problem? Please describe.**
Yes, the library does not contain randomized quick sort algorithm

**Describe the solution you'd like**
Will implement a function randomizedQuickSort(arr,hint)

**Describe alternatives you've considered**
nothing as of now

Can I work on this?

**Comment by Abhijit2505** [comment]
Well, the quick sort algorithm is already present and we don't want any other enhancement of quicksort in our package.

Closing the issue.
