### ISSUE TITLE
Min Steps to 1 [SWOC]

### ISSUE THREAD

**Issue by shradhaagarwal01** [edualgo/eduAlgo#118]
Hello sir, I am a participant in SWOC 2021, I would like to contribute by adding the code for Min Steps to 1 In Dynamic Programming.
Kindly assign this issue to me.
Thank you.

**Comment by Abhijit2505** [comment]
See the minimum step to 1 depends on the condition given, we already have a stair case method in our dp module, do you want to add something else ?

**Comment by shradhaagarwal01** [comment]
Yes, Matrix Chain Multiplication Problem in Dynamic Programming.
