### ISSUE TITLE
Some famous algorithms not yet included [SWoC]

### ISSUE THREAD

**Issue by AdityaArunSharma** [edualgo/eduAlgo#120]
Found some famous algorithms that are not yet included in the library. Please go through it and mention those on which I can work

Dynammic Programming based :-
1. count all possible paths from top left to bottom right in a square matric
2. longest palindromic subsequence
3. number of unique (structurally different) BST with given number of nodes
4. rod cutting problem

Greedy based :-
1. fractional knapsnack
2. minimum spanning tree
3. activity selection

Tree based :-
1. symmetric tree
2. level order traversal
3. zigziag level order traversal
4. maximum depth of binary tree
5. invert binary tree

**Comment by Rahul555-droid** [comment]
Hi @Abhijit2505 .

I also noticed that some of the major algorithms in string pattern matching and many others are not yet available here.
I would also want to work on these algorithms for SWOC if available!

Thanks.

**Comment by Abhijit2505** [comment]
We know there are algorithms which are not included in the package.  Don't open an issue collectively, instead create issues of algorithms one by one.
