### ISSUE TITLE
Fibonacci Numbers [SWoC]

### ISSUE THREAD

**Issue by fomalhauting** [edualgo/eduAlgo#121]
**Is your feature request related to a problem? Please describe.**
I would like to add Fibonacci Numbers Algorithms

**Describe the solution you'd like**
Fibonacci Number's algorithms

**Describe alternatives you've considered**

**Additional context**

**Comment by fomalhauting** [comment]
Can I work on this?

**Comment by Abhijit2505** [comment]
@itsIapetus get started

**Comment by xlrnz** [comment]
I've write a little implementation for this can i show you?

**Comment by xlrnz** [comment]
I've open a pull request for this :) it's very simple and basic but I think it's a good start point! #124

**Comment by Abhijit2505** [comment]
> I've open a pull request for this :) it's very simple and basic but I think it's a good start point! #124

I have not assigned you the task, only open a PR, after getting assigned.

**Comment by HarshKhilawala** [comment]
@Abhijit2505 Please assign me to this issue !
(Update) Sorry, I didn't notice that PR has already been merged for this issue. Please close this issue

**Comment by anirudhsai20** [comment]
Hi @Abhijit2505 . Can I please work on this under  SWOC?
