### ISSUE TITLE
(PYL-W0127) Variable assigned to itself

### ISSUE THREAD

**Issue by Abhijit2505** [edualgo/eduAlgo#126]
## Description
Variable is being assigned to itself.

## Occurrences
There is 1 occurrence of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Abhijit2505/eduAlgo/issue/PYL-W0127/occurrences/](https://deepsource.io/gh/Abhijit2505/eduAlgo/issue/PYL-W0127/occurrences/)

**Comment by avnish100** [comment]
Hi the deepsource link doesnt work.

**Comment by Abhijit2505** [comment]
@avnish100 sorry about that. I am closing the issue.
