### ISSUE TITLE
[SWOC] Search Algorithms

### ISSUE THREAD

**Issue by fomalhauting** [edualgo/eduAlgo#131]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to add:
Binary search algo
Sublinear search algo
Bilinear search algo
Random select algo

**Describe alternatives you've considered**

**Additional context**

**Comment by itsIapetus** [comment]
@Abhijit2505 Can I go ahead with these?

**Comment by fomalhauting** [comment]
@Abhijit2505  Can I go ahead with these?

**Comment by fomalhauting** [comment]
@Abhijit2505 could you assign it to me?

**Comment by Abhijit2505** [comment]
@itsIapetus, Binary Search Algo is already present, please go through the source code,

Please add only the Sublinear Search algo

**Comment by itsIapetus** [comment]
I checked binary search is also not in it, could I add that too?

**Comment by fomalhauting** [comment]
Okay sure, thank you.
