### ISSUE TITLE
[SWOC] Cryptography algorithms

### ISSUE THREAD

**Issue by fomalhauting** [edualgo/eduAlgo#133]
**Is your feature request related to a problem? Please describe.**
I would like to add Cryptography Algorithms
Affine Cipher 
Burrows-Wheeler Transform
Caesar Cipher
RSA Algorithm
XOR Cipher
Vigenere Cipher

**Describe the solution you'd like**
Cryptography Algorithms

**Describe alternatives you've considered**

**Additional context**

**Comment by fomalhauting** [comment]
@Abhijit2505 Can I work on this? Please assign it to me, thank you.

**Comment by Abhijit2505** [comment]
> @Abhijit2505 Can I work on this? Please assign it to me, thank you.

One issue at a certain time

**Comment by fomalhauting** [comment]
@Abhijit2505 Can I work on this now?
