### ISSUE TITLE
Segment Tree Algorithms Addition

### ISSUE THREAD

**Issue by krypticmouse** [edualgo/eduAlgo#135]
**Is your feature request related to a problem? Please describe.**
I would like to add Segment Tree Implementation under algorithm folder.

**Describe the solution you'd like**
Implementing Segment Tree with various range based query implementation.

**Describe alternatives you've considered**

**Additional context**

**Comment by krypticmouse** [comment]
@Abhijit2505 Can I work on this issue?

**Comment by Abhijit2505** [comment]
@krypticmouse , don't forget to add the hint methods as well.

**Comment by Abhijit2505** [comment]
Are you participating in Script Winter of code ?

**Comment by krypticmouse** [comment]
No. Is that what Swoc is? Everyone was writing it so I did the same thing.
Sry I'm quite new to open source😅

**Comment by krypticmouse** [comment]
> Are you participating in Script Winter of code ?

No

**Comment by krypticmouse** [comment]
> @krypticmouse , don't forget to add the hint methods as well.

Sure will add it too.

**Comment by Abhijit2505** [comment]
> > Are you participating in Script Winter of code ?
> 
> No

Please remove the [SWOC] word from the issue
