### ISSUE TITLE
Create a Stack

### ISSUE THREAD

**Issue by gnurenga** [edualgo/eduAlgo#14]
Stack is an abstract data type 

- User can insert object in to a stack
-  Remove the recent added element from the stack
- Check is the stack is empty 
- Calculate the length of the stack

**Comment by gnurenga** [comment]
@Abhijit2505 Can you assign this task I will work on this

**Comment by Abhijit2505** [comment]
@gnurenga you may get started with the issue, don't forget to add the hint methods as well.

**Comment by gnurenga** [comment]
@Abhijit2505 The Stack concept comes under data structures we cannot call exactly an algorithm. It is actually called Abstract Data Type[1]. I hope it doesn't matter for this project. Just want to ensure that. 

[1].. https://en.wikipedia.org/wiki/Stack_(abstract_data_type)

**Comment by Abhijit2505** [comment]
> @Abhijit2505 The Stack concept comes under data structures we cannot call exactly an algorithm. It is actually called Abstract Data Type[1]. I hope it doesn't matter for this project. Just want to ensure that.
> 
> [1].. https://en.wikipedia.org/wiki/Stack_(abstract_data_type)

yes no issues, I know about stack and you can still contribute.

**Comment by gnurenga** [comment]
@Abhijit2505 I have sent a pull request #18

**Comment by Abhijit2505** [comment]
@all-contributors please add @gnurenga  for code
