### ISSUE TITLE
[SWOC] Trapping Rainwater

### ISSUE THREAD

**Issue by HarshKhilawala** [edualgo/eduAlgo#141]
**Describe the solution you'd like**
Adding Trapping Rainwater Problem (Companies: Facebook, Microsoft , Google, Oracle, Airbnb, LinkedIn) (Difficulty: Hard)

**Comment by HarshKhilawala** [comment]
@Abhijit2505 Please assign me to work on adding this to Dynamic Programming directory.

**Comment by HarshKhilawala** [comment]
@Abhijit2505 Please let me know

**Comment by Abhijit2505** [comment]
@HarshKhilawala , eduAlgo is not a problem addition package. Please check the Source code.
