### ISSUE TITLE
StairCase Search in Row and Column sorted matrix

### ISSUE THREAD

**Issue by kiruba-r11** [edualgo/eduAlgo#146]
**Is your feature request related to a problem? Please describe.**
`Staircase search` is also commonly known as Search in a Row and Column sorted matrix.

**Describe the solution you'd like**
Implement the optimized solution for this problem

**Comment by kiruba-r11** [comment]
@Abhijit2505 Can I work on this issue

**Comment by Abhijit2505** [comment]
@kiruba-r11 please get started.

**Comment by spartan289** [comment]
@Abhijit2505 Can i work on this issue

**Comment by Abhijit2505** [comment]
@spartan289 Please get started

**Comment by spartan289** [comment]
hey @Abhijit2505, I have created the function but where I have to add it and do I indeed explain it.
