### ISSUE TITLE
Quick Sort using Median of Medians Algorithm

### ISSUE THREAD

**Issue by beekayg15** [edualgo/eduAlgo#147]
**Is your feature request related to a problem? Please describe.**
`Quick Sort` algorithm is a basic fast-searching algorithm with a time complexity of `O(nlogn)`

**Describe the solution you'd like**
`Quick Sort` is a well known algorithm used to sort an array with a NlogN time complexity. However in the worst case scenario it takes a time complexity of O(n^2) to sort an array of length N(i.e when already sorting in asc. or desc. order). Therefore the it can be  combined with `the median of medians` algorithm(i.e to choose the best pivot) to ensure the time complexity to be O(nlogn).

**Comment by beekayg15** [comment]
@Abhijit2505 I kindly request you to permit me to work on the issue. Thanks in advance.

**Comment by Abhijit2505** [comment]
Quick sort is already present.
