### ISSUE TITLE
Hint is missing in Fibonacci Series

### ISSUE THREAD

**Issue by Manoj-Paramsetti** [edualgo/eduAlgo#149]
## Description
Adding hint and removing the math module in the Fibonacci series program

## Is your feature request related to a problem? Please describe.
It's somewhat related to a problem. Actually, the hint is missing in the Fibonacci series and the Math module is imported unnecessarily 

## Describe the solution you'd like
* I like to add the `hint` message in the Fibonacci series
* Remove Math module

**Comment by Abhijit2505** [comment]
@Manoj-Paramsetti please get started.

**Comment by Manoj-Paramsetti** [comment]
Okay

**Comment by sumitchouhan13** [comment]
Could you please explain what does adding hint here means ?

**Comment by Manoj-Paramsetti** [comment]
@Abhijit2505 Completed! check the pull request [#151](https://github.com/edualgo/eduAlgo/pull/151)
I added the pull request related to issue #150 and this issue to reduce the commit numbers
