### ISSUE TITLE
Create a queue

### ISSUE THREAD

**Issue by gnurenga** [edualgo/eduAlgo#15]
- Add element to a queue
- Remove element from a queue
- Check queue is empty 
- find the length of queue
- get the first added element in the queue using a function

**Comment by gopalngk** [comment]
I will start looking to implement queue data structure with the mentioned options

**Comment by Abhijit2505** [comment]
@gopalngk You may start with the issue, don't forget to add the hint methods as well.

**Comment by gopalngk** [comment]
@Abhijit2505  I have added the Queue data structure in pull request #22
