### ISSUE TITLE
__init__ file is empty

### ISSUE THREAD

**Issue by Manoj-Paramsetti** [edualgo/eduAlgo#150]
**Is your feature request related to a problem? Please describe.**
\_\_init__.py is empty and doesn't contain print_msg_box()  function in `/edualgo/maths/__init__.py`

**Describe the solution you'd like**
Adding the print_msg_box function in `/edualgo/maths/__init__.py`

**Additional context**
Importing print_msg_box directly from the eduAlgo package is not appreciated

**Comment by Abhijit2505** [comment]
@Manoj-Paramsetti please get started.

**Comment by Abhijit2505** [comment]
@Manoj-Paramsetti please get started.

**Comment by Manoj-Paramsetti** [comment]
@Abhijit2505 Completed! check the pull request [#151](https://github.com/edualgo/eduAlgo/pull/151)
