### ISSUE TITLE
eduAlgo logo not displaying in About Us section

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [edualgo/eduAlgo#152]
Logo not displaying in about us section.

![image](https://user-images.githubusercontent.com/56196640/114546686-190b1800-9c7b-11eb-83aa-8595f015a17e.png)

**Comment by QAZIMAAZARSHAD** [comment]
Assign me this issue and I'll fix it.

**Comment by Abhijit2505** [comment]
@QAZIMAAZARSHAD this is not the project where the website code is present.
