### ISSUE TITLE
Pattern Searching::Mismatch Observation - Implement KMP Algorithm

### ISSUE THREAD

**Issue by Abhijit2505** [edualgo/eduAlgo#159]
Wikipedia Says,
> In computer science, the Knuth–Morris–Pratt string-searching algorithm (or KMP algorithm) searches for occurrences of a "word" W within a main "text string" S by employing the observation that when a mismatch occurs, the word itself embodies sufficient information to determine where the next match could begin, thus bypassing re-examination of previously matched characters.

Read about the algorithm [here](https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm).

### Acceptance Condition
- Code is written with proper mentions of edge cases
- Well commented code
- Well documentation(refer to codebase)

**Comment by Audarya07** [comment]
Hey @Abhijit2505 
I would like to add KMP pattern search algo in python to the `edualgo/algorithms/` directory.
Please assign the issue to me

**Comment by Abhijit2505** [comment]
@Audarya07 please get started

**Comment by Audarya07** [comment]
Hey @Abhijit2505 
I have raised a PR.
Please have a look and let me know if any changes are required from my end
