### ISSUE TITLE
(PTC-W0068) Consider using identity comparison with singleton

### ISSUE THREAD

**Issue by Abhijit2505** [edualgo/eduAlgo#163]
## Description
Comparisons to the singleton objects, like `True`, `False`, and `None`, should be done with identity, not equality. Use `is` or `is not`.

## Occurrences
There are 80 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/edualgo/eduAlgo/issue/PTC-W0068/occurrences/](https://deepsource.io/gh/edualgo/eduAlgo/issue/PTC-W0068/occurrences/)

**Comment by pawankm21** [comment]
Would like to work on this issue

**Comment by Rutvik2610** [comment]
Hi, could you assign this issue to me?
