### ISSUE TITLE
Delete linked list node

### ISSUE THREAD

**Issue by hussamEL-Hwary** [edualgo/eduAlgo#173]
In **linkedlist > list_algorithms>delete_node** method will cause a problem in these cases.

- The node is the tail node `node.next.next` will fail
- The node is `None`
- If the node is the head node then we will lose head after deleting the node

Recommended solution :bulb:
A second parameter should be passed for the previous node to correctly delete the node.

**Comment by Abhijit2505** [comment]
@hussamEL-Hwary please fix it up, it's a valid issue.

**Comment by hussamEL-Hwary** [comment]
Thank you! I will work on it.
