### ISSUE TITLE
Stack sequence finder

### ISSUE THREAD

**Issue by suvanbalu** [edualgo/eduAlgo#177]
Can I add stack push and pop sequence for a given list of push and pop ?
As it is a popular question in stack!

**Comment by Abhijit2505** [comment]
@suvanbalu please get started.

**Comment by Abhijit2505** [comment]
@suvanbalu Please get started, and acknowledge.

**Comment by suvanbalu** [comment]
Sorry for the delay ! it will be uploaded today
