### ISSUE TITLE
Linked List Algorithm Implementations (Intermediate)

### ISSUE THREAD

**Issue by Abhijit2505** [edualgo/eduAlgo#2]
Here is a list of algorithmic implementations using a linked list,

* Design Linked List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Rotate List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Insert Into a Sorted Circular Linked List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Add Two Numbers - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Remove Nth Node From End of List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Copy List with Random Pointer - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Remove Duplicates From The Sorted List (Second Version) - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Reorder List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Linked List Cycle (Second Version) - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Reverse Linked List (Second Version) - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Linked List In Binary Tree - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Insertion Sort List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Remove Zero-Sum Consecutive Nodes from Linked List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Partition List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Sort List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Design Phone Directory - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Convert Sorted List to Binary Search Tree - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Swap Nodes in Pairs - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Split Linked List in Parts - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Add Two Numbers(Second Version) - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Flatten a Multilevel Doubly Linked List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Odd-Even Linked List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Linked List Components - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Next Greater Node in Linked List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Plus One Linked List - <img src ="https://img.shields.io/badge/-intermediate-orange">
* Convert Binary Search Tree to Sorted Doubly Linked List - <img src ="https://img.shields.io/badge/-intermediate-orange">

Work upon these algorithms are going on.

**Comment by Devansu-Yadav** [comment]
Hi there! I found this Project on FOSS United Foundation's FOSS HACK 2020 event website. I have the read the Documentation and I wanted to contribute to the Sorting Algorithms and its Visualization as mentioned on the Documentation under the section saying "Algorithms Yet to Publish".
