### ISSUE TITLE
Add Selectionsort algorithm

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [edualgo/eduAlgo#33]
Hello , I want to contribute to add sorting algorithm Selectionsort.

**Comment by Abhijit2505** [comment]
@ShraddhaDevaiya I think Selection Sort algorithm is already available. Please have a check.

**Comment by ShraddhaDevaiya** [comment]
Sorry ,yeah  it is available. can you suggest any other one if possible?

**Comment by Abhijit2505** [comment]
@ShraddhaDevaiya , you may run through the entire codebase once, in order to learn which algorithms can be added.
