### ISSUE TITLE
Algorithms Addition

### ISSUE THREAD

**Issue by Abhijit2505** [edualgo/eduAlgo#4]
Cheers !! PyCon Devsprint is here 🎉🎉

You may add any of your favourite algorithms to our modules.

Just comment the name of the algorithms below in this issue and I will be assigning you the same.
**Join the discuss here - [eduAlgo Zulip](https://pyconindia.zulipchat.com/#narrow/stream/257423-2020.2Fdevsprint/topic/eduAlgo)**

### Assigned Issues

* Delete nth node from the end in a Linked List - @Abhaskar1
* Insertion Sort - @24apurv
* Binary Search algorithm based on Divide and Conquer Methodology - @KanakKvdi
* Mege sort and Shell Sort - @nihilistdbanana

**Comment by Abhaskar1** [comment]
Hello, I would like to work on "Delete nth Node from end in a linked list"

**Comment by Abhijit2505** [comment]
> Hello, I would like to work on "Delete nth Node from end in a linked list"

@Abhaskar1 you may get started with that, also don't forget to add a hint method for the same. I am assigning you the issue.

**Comment by 24apurv** [comment]
Hey can I add implementation of insertion sort?

**Comment by Abhijit2505** [comment]
> Hey can I add implementation of insertion sort?

@24apurv yes, you may proceed with that. Don't forget to add the hint method as well.

**Comment by Abhijit2505** [comment]
@all-contributors please add @Abhaskar1 for code

**Comment by Abhijit2505** [comment]
@all-contributors please add @24apurv for code

**Comment by KanakKvdi** [comment]
Greetings! I'd love to add Binary Search algorithm based on Divide and Conquer methodology. 
May I?

**Comment by Abhijit2505** [comment]
> Greetings! I'd love to add Binary Search algorithm based on Divide and Conquer methodology.
> May I?

@KanakKvdi you may continue with this issue.

**Comment by KanakKvdi** [comment]
@Abhijit2505 Thank you!

**Comment by KanakKvdi** [comment]
@Abhijit2505 Just made a pull request.

**Comment by Abhijit2505** [comment]
@all-contributors please add @KanakKvdi  for code

**Comment by KanakKvdi** [comment]
Yayyy!!!

**Comment by nihilistdbanana** [comment]
Hi can I add merge and shell sort?

**Comment by Abhijit2505** [comment]
> Hi can I add merge and shell sort?

Yes you may get started with the issue.

**Comment by Abhijit2505** [comment]
@all-contributors please add @nihilistdbanana  for code
