### ISSUE TITLE
Potential Suggestions

### ISSUE THREAD

**Issue by HarshCasper** [edualgo/eduAlgo#44]
## Description
 
Hi @Abhijit2505

I'm in total love with your Project, especially since I got to use your Package for a personal Project. That's a great work put up by you and the Team at EduAlgo. 

I would like to highlight few issues in the Project Code right now: 

- You can stop tracking your VS Code Configuration by removing `.vscode`
- You can remove the Project Build `build/lib/edualgo` from the Repository.
- You can remove the Egg Packaging `eduAlgo.egg-info` from the Repository.

These are healthy suggestions to keep the Project hassle-free while installation and preventing leaks.

**Comment by Abhijit2505** [comment]
@HarshCasper, thank you for the suggestion. 
We will change the project structure into a simpler one, rather than uploading the direct package structure.

Thanks again 😀

**Comment by Abhijit2505** [comment]
> ## Description
> Hi @Abhijit2505
> 
> I'm in total love with your Project, especially since I got to use your Package for a personal Project. That's a great work put up by you and the Team at EduAlgo.
> 
> I would like to highlight few issues in the Project Code right now:
> 
> * You can stop tracking your VS Code Configuration by removing `.vscode`
> * You can remove the Project Build `build/lib/edualgo` from the Repository.
> * You can remove the Egg Packaging `eduAlgo.egg-info` from the Repository.
> 
> These are healthy suggestions to keep the Project hassle-free while installation and preventing leaks.

One more thing, we would like to know more about how eduAlgo has been a help in your personal project. We would really like to hear from you regarding the package use at our email - <a href="mailto:founder.edualgo@gmail.com">founder mail</a>.

Thank you so much for taking the time and reaching out to us with the suggestions.

**Comment by Abhijit2505** [comment]
@all-contributors please add @HarshCasper for mentoring

**Comment by Abhijit2505** [comment]
@all-contributors please add @HarshCasper

**Comment by Abhijit2505** [comment]
@all-contributors please add @HarshCasper for Mentoring

**Comment by Abhijit2505** [comment]
@all-contributors please add @HarshCasper for coding
