### ISSUE TITLE
Add Dijkstra algorithms 

### ISSUE THREAD

**Issue by Abhijit2505** [edualgo/eduAlgo#53]
The python package currently doesn't cover Dijkstra Algorithm

- Dijkstra Algorithm - @Siddhant-K-code

**Comment by Siddhant-K-code** [comment]
Can i do this for `Dijkstra` ?

**Comment by Abhijit2505** [comment]
> Can i do this for `Dijkstra` ?

You can add **Dijkstra algorithm in python**, don't forget to go through our codebase, Also don't forget to add the `hint` method as well.

**Comment by Siddhant-K-code** [comment]
What do you mean by "hint" ?

**Comment by Abhijit2505** [comment]
> What do you mean by "hint"?

Before contributing to any opensource-project, go through the code files and the project tree structure. Watch the demo videos that are provided.

In the demo video, you can see the hint method in action.

also, explore the project files, most of them contain a `hint` method as well.

**Comment by Siddhant-K-code** [comment]
please check #60

**Comment by sunanda690** [comment]
> The python package currently doesn't cover important graph-based algorithms like the TSP, Metric TSP, MST (Prim/Kruskal), Dijkstra, Bipartite graph checking etc.
> 
> You are expected to pick only one algorithm and add the **code** as well as it's **hint method** and the **documentation** for the package.
> 
> * Dijkstra Algorithm - @Siddhant-K-code

Hello, Can I do MST(prim's and Kruskal)?

**Comment by Abhijit2505** [comment]
> > The python package currently doesn't cover important graph-based algorithms like the TSP, Metric TSP, MST (Prim/Kruskal), Dijkstra, Bipartite graph checking etc.
> > You are expected to pick only one algorithm and add the **code** as well as it's **hint method** and the **documentation** for the package.
> > 
> > * Dijkstra Algorithm - @Siddhant-K-code
> 
> Hello, Can I do MST(prim's and Kruskal)?

@sunanda690 would you mind telling me are you a regular contributor or being a part of us through any Winter Of Code program ?

**Comment by AdityaArunSharma** [comment]
@Abhijit2505  The graph that will be passed to function should be in the adjacency list form right?

**Comment by amoghatsunil** [comment]
@Abhijit2505  Can i do A* Algorithm?

**Comment by AdityaArunSharma** [comment]
@Abhijit2505 Can I do Bi-Partited graph checking algorithm ? ( SWoC)

**Comment by Abhijit2505** [comment]
> @Abhijit2505 Can I do Bi-Partited graph checking algorithm ? ( SWoC)

This is not an issue for SWoC. The internal developer team is working on it.
