### ISSUE TITLE
Add Dynamic Programming Problem

### ISSUE THREAD

**Issue by Prakhar-Mangal** [edualgo/eduAlgo#88]
There are various popular Dynamic Programming Problems and I'm starting with:

-  Kadane’s Algorithm

**Comment by khushibalyan220101** [comment]
I wanna contribute to this. Please assign it to me.

**Comment by Prakhar-Mangal** [comment]
> I wanna contribute to this. Please assign it to me.

It's already taken by me.

**Comment by 0xamitdutta** [comment]
> > I wanna contribute to this. Please assign it to me.
> 
> It's already taken by me.

Shouldn't you wait for the Project Admin to assign it first. Additionally, Dynamic Programming is a very vast topic. I'm pretty sure more than one person can contribute towards it.

**Comment by Abhijit2505** [comment]
> > > I wanna contribute to this. Please assign it to me.
> > 
> > 
> > It's already taken by me.
> 
> Shouldn't you wait for the Project Admin to assign it first. Additionally, Dynamic Programming is a very vast topic. I'm pretty sure more than one person can contribute towards it.

@Amitdutta7 he is actually a part of the eduAlgo team as well as a contributor for another opensource program. We had a firm discussion before assigning this to him. Hope it clears your doubt.
