### ISSUE TITLE
Adding  5 different  searching, sorting algorithms

### ISSUE THREAD

**Issue by nitya123-github** [edualgo/eduAlgo#96]
Adding 5 different searching, sorting algorithms  in the project such as insertion ,linear search ,binary  search, selection sort, merge sort ,quick sort,heap sort and also adding the worst,best,average complexities of each algorithms

**Comment by nitya123-github** [comment]
can you please assign this to me @Abhijit2505 ?

**Comment by Utkarsh-Agarwal-585** [comment]
Sir, I'm ready to contribute. Could you please assign it to me....

**Comment by Abhijit2505** [comment]
> Adding 5 different searching, sorting algorithms in the project such as insertion ,linear search ,binary search, selection sort, merge sort ,quick sort,heap sort and also adding the worst,best,average complexities of each algorithms

Did you check the code-base of eduAlgo, These algorithms already exists in our package.

Check our documentation for more info - https://edualgo.github.io/documentation/
